const statusEl=document.getElementById("certificateStatus"),gridEl=document.getElementById("certificateGrid");
function githubApiUrl(){const c=GITHUB_CONFIG;return `https://api.github.com/repos/${encodeURIComponent(c.owner)}/${encodeURIComponent(c.repo)}/contents/${c.certificateFolder}?ref=${encodeURIComponent(c.branch)}`}
function rawUrl(path){const c=GITHUB_CONFIG;return `https://raw.githubusercontent.com/${encodeURIComponent(c.owner)}/${encodeURIComponent(c.repo)}/${encodeURIComponent(c.branch)}/${path.split("/").map(encodeURIComponent).join("/")}`}
function prettyName(filename){return filename.replace(/\.[^/.]+$/,'').replace(/[-_]+/g,' ').replace(/\b\w/g,ch=>ch.toUpperCase())}
function isSupported(filename){return /\.(png|jpe?g|webp|gif|pdf)$/i.test(filename)}
function fileType(filename){return /\.pdf$/i.test(filename)?"pdf":"image"}
function createCard(file){const type=fileType(file.name),url=rawUrl(file.path),article=document.createElement("article");article.className="certificate-card";const preview=document.createElement("div");preview.className="certificate-image";
if(type==="pdf"){const iframe=document.createElement("iframe");iframe.className="pdf-preview";iframe.src=`${url}#toolbar=0&navpanes=0&scrollbar=0`;iframe.title=`Preview ${file.name}`;preview.appendChild(iframe);const label=document.createElement("span");label.className="pdf-label";label.textContent="PDF";preview.appendChild(label)}else{const img=document.createElement("img");img.src=url;img.alt=prettyName(file.name);img.loading="lazy";preview.appendChild(img)}
const button=document.createElement("button");button.className="view-btn";button.textContent=type==="pdf"?"Buka PDF":"Lihat Sertifikat";button.addEventListener("click",()=>openCertificate(file.name,url,type));preview.appendChild(button);
const info=document.createElement("div");info.className="certificate-info";const org=document.createElement("p");org.className="certificate-org";org.textContent=type==="pdf"?"Dokumen PDF":"Sertifikat";const title=document.createElement("h3");title.textContent=prettyName(file.name);const date=document.createElement("p");date.textContent="File dari GitHub";const badge=document.createElement("span");badge.className="certificate-badge";badge.textContent=type.toUpperCase();info.append(org,title,date,badge);article.append(preview,info);return article}
async function loadCertificates(){const c=GITHUB_CONFIG;if(!c.owner||c.owner.includes("USERNAME_")||!c.repo||c.repo.includes("NAMA_")){statusEl.className="certificate-status error";statusEl.textContent="Belum dikonfigurasi. Buka config.js lalu isi username GitHub dan nama repository.";return}try{const response=await fetch(githubApiUrl(),{headers:{Accept:"application/vnd.github+json"}});if(!response.ok)throw new Error(`GitHub API ${response.status}`);const files=await response.json();const certificates=files.filter(item=>item.type==="file"&&isSupported(item.name)).sort((a,b)=>a.name.localeCompare(b.name,"id"));gridEl.innerHTML="";if(!certificates.length){statusEl.textContent="Belum ada sertifikat di folder GitHub.";return}statusEl.textContent=`${certificates.length} sertifikat ditemukan.`;certificates.forEach(file=>gridEl.appendChild(createCard(file)))}catch(error){console.error(error);statusEl.className="certificate-status error";statusEl.textContent="Sertifikat gagal dimuat. Pastikan repository GitHub public, nama repository dan branch di config.js benar, serta folder assets/certificates sudah ada."}}
function openCertificate(name,url,type){const modal=document.getElementById("certificateModal"),body=document.getElementById("modalBody");body.innerHTML="";if(type==="pdf"){const iframe=document.createElement("iframe");iframe.src=`${url}#toolbar=1&navpanes=0`;iframe.title=name;body.appendChild(iframe)}else{const img=document.createElement("img");img.src=url;img.alt=name;body.appendChild(img)}modal.classList.add("show");document.body.style.overflow="hidden"}
function closeCertificate(event){if(!event||event.target.id==="certificateModal"||event.target.classList.contains("close")){document.getElementById("certificateModal").classList.remove("show");document.getElementById("modalBody").innerHTML="";document.body.style.overflow=""}}
document.addEventListener("keydown",event=>{if(event.key==="Escape")closeCertificate()});loadCertificates();
